# 内存
megs: 32

# BIOS（务必用绝对路径！$BXSHARE 经常失效）
# romimage: file=/usr/share/bochs/BIOS-bochs-latest
romimage: file=/usr/share/bochs/BIOS-bochs-legacy
vgaromimage: file=/usr/share/bochs/VGABIOS-lgpl-latest

# 启动设备
boot: disk
ata0: enabled=1, ioaddr1=0x1f0, ioaddr2=0x3f0, irq=14
ata0-master: type=disk, path="disk.img", mode=flat, cylinders=20, heads=16, spt=63

# 日志
log: bochs.log

# 鼠标关闭
mouse: enabled=0

# 调试必须！开启内置调试器
magic_break: enabled=1
